dist: bionic
language: python
python:
- '3.7'
- '3.8'
before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
install:
- pip install ".[test]"
script:
- mypy --ignore-missing-imports src
deploy:
  - provider: pypi
    user: __token__
    password:
      secure: nw/OVEc5uOm00rfcJC0yoleD9yPafZ6khNK8+v3/bGBdzeauqu0zhic6sqLFzRfd3ejrB7AooqdaqxgZJu8LIszkfSc9NXWnTyQIFRescLeQts02Fv7MsELlmmkoODnTHw2mzPmsLGoUCM9SxcUJ9ld2WkfD7Ai+cC3TPPoBzXxn5x2Y/ocGRkY4WDDVKdDC1smlvFXwdWwghyQEf/vWLOwLQ+WawxUAbwChqlxDBEJ+KQk2iLMKRp8umRl4fQpMoGtzirZKFanZz2BxdU4N0c/hyXhmhbXqSSmM+Vz31AIICfVDSjD/oRuhhrfQBxD7NhfowsxEmjll/y1wCJnW9rKbwDeS0oWm4jVclLXSlRSwIYyZnm/S9bwXkfba8Yx/UWwQ3GEi40S/rTqUhBBfXb5uZqIg40zX2IYsSm8+ORgwWlct4HuT5SbAgU1dsRmkjnixoebUIC4Rc8djBwRbrQXlHYFxehDxHycGEFedeC9K5w4JLgX2peicorb5/a0nnG7Spi5iOhnBFj8eJNV0gEBcA901PU8isSQuq3R5bFbdkAE6iNM5Oydk0h/i+9IkPQuEjMosNN1/1rTaA/koiu5tSUscoEV4lvCQRymKe/JuUNmnKF2QIBFsddZuUjeo+RLRx7RugIjD6icrukQjLWpA0108RtRTpRYN7TCszAM=
    on:
      tags: true
    skip_existing: true
  - provider: script
    script: bash conda-build/travis_deploy.sh
    on:
      tags: true
    skip_existing: true
